quiz/urls.py
from django.urls import path
from . import views


app_name = 'quiz'

urlpatterns = [
    path('create_quiz_category/', views.create_quiz_category, name='create_quiz_category'),
    path('add_quiz_question/', views.add_quiz_question, name='add_quiz_question'),
    path('show_quiz_question/', views.show_quiz_question, name='show_quiz_question'),
    path('quiz_index/', views.quiz_index, name='quiz_index'),
    path('delete_quiz_question/<int:question_id>/', views.delete_quiz_question, name='delete_quiz_question'),
    path('update_quiz_category/<int:category_id>/', views.update_quiz_category, name='update_quiz_category'),
    path('show_quiz_category/', views.show_quiz_category, name='show_quiz_category'),
    path('delete_quiz_category/<int:category_id>', views.delete_quiz_category, name='delete_quiz_category'),
    path('add_answer_to_questions/<int:question_id>/', views.add_answer_to_questions, name='add_answer_to_questions'),
    
    
    path('view_quiz/<int:category_id>/', views.view_quiz, name='view_quiz'),
    path('submit_quiz/<int:category_id>/', views.submit_quiz, name='submit_quiz'),
    path('quiz_result/<int:category_id>/<int:user_score_id>/', views.quiz_result, name='quiz_result'),

    
    
]

quizapplication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_registration.urls')),
    path('quiz/', include('quiz.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_registration/urls.py
from django.urls import path
from . import views

app_name = 'user_registration'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_profile/<int:id>/', views.user_profile, name="user_profile"),
    path('change_password/<int:id>/', views.change_password, name='change_password'),
    path('upload_profile_image/<int:id>/', views.upload_profile_image, name='upload_profile_image'),
    path('update_profile/<int:id>/', views.update_profile, name='update_profile'),
    path('user_list/', views.user_list, name='user_list'),
]

user_registration/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    user = models.OneToOneField(User, related_name="userinfo", on_delete=models.CASCADE)
    # address
    address = models.CharField(max_length=100, blank=True)
    # phone
    phone = models.CharField(max_length=15, blank=True)

    #Profile image
    profile_image = models.ImageField(upload_to='profile_image', blank=True, default='image/no-image.svg')

    def __str__(self):
        return self.user.username

user_registration/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')


class UserInfoForm(forms.ModelForm):
    profile_image = forms.ImageField(required=False)
    class Meta():
        model = UserInfo
        fields = ('address', 'phone', 'profile_image')
        

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

user_registration/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.contrib import messages


from .forms import UserForm, UserInfoForm, UserUpdateForm
from .models import UserInfo
from django import forms


"""This function renders homepage"""
def index(request):
    return render(request, "user_registration/index.html")



"""This function registers the user."""
def register(request):
    registered = False

    if request.method == "POST":
        try:
            user_form = UserForm(data=request.POST)
            info_form = UserInfoForm(data=request.POST)

            if user_form.is_valid() and info_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                info = info_form.save(commit=False)  # Shanka
                info.user = user

                if "profile_image" in request.FILES:
                    info.profile_image = request.FILES["profile_image"]
                else:
                    info.profile_image = "image/no-image.svg"

                info.save()

                registered = True
                messages.success(request, "User registration successfull. Please log in.")
                return redirect(reverse("user_registration:user_login"))

            else:
                for field_errors in user_form.errors.values():
                    for error in field_errors:
                        messages.error(request, error)
              
                        
                for field_errors in info_form.errors.values():
                    for error in field_errors:
                        messages.error(request, error)
                
        except Exception as e:
            messages.error(request, f"Error: {str(e)}")
    else:
        user_form = UserForm()
        info_form = UserInfoForm()

    return render(
        request,
        "user_registration/register.html",
        {"user_form": user_form, "info_form": info_form, "registered": registered},
    )



"""This function logs in"""
def user_login(request):
    if request.method == "POST":
        try:
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    return redirect("quiz:quiz_index")
                else:
                    messages.error(request, "Account is not active.")
            else:
                messages.error(request, "Invalid Username or Password. Please Try Again!!")
        except Exception as e:
            messages.error(request, f"Error: {str(e)}")

    return render(request, "user_registration/login.html")



"""This function logs out"""
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("user_registration:index"))





"""This function renders profile"""
@login_required
def user_profile(request, id):
    try:
        user = User.objects.get(id=id)
        user_info = UserInfo.objects.get(user=user)
        return render(
            request,
            "user_registration/user_profile.html",
            {"user": user, "user_info": user_info},
        )
    except UserInfo.DoesNotExist:
        return redirect("user_registration:user_login")





"""This function updates the password"""
@login_required
def change_password(request, id):
    try:
        id = request.user.id
        if request.method == "POST":
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)
                messages.success(request, "Your Password Has Been Changed Successfully.")
                return redirect("user_registration:user_profile", id)
            else:
                messages.error(request, "Something is wrong please try again.")
        else:
            password_form = PasswordChangeForm(request.user)
    except User.DoesNotExist:
        messages.error(request, "User does not exist.")
        return redirect("user_registration:user_login")

    return render(
        request,
        "user_registration/change_password.html",
        {"password_form": password_form},
    )




"""This function updates the image on profile page"""
@login_required
def upload_profile_image(request, id):
    try:
        user = get_object_or_404(User, id=id)
        try:
            user_info = UserInfo.objects.get(user=user)
        except UserInfo.DoesNotExist:
            user_info = UserInfo(user=user)
            user_info.save()

        if request.method == 'POST':
            form = UserInfoForm(request.POST, request.FILES, instance=user_info)
            if form.is_valid():
                new_user_info = form.save(commit=False)

                if 'profile_image' in request.FILES:
                    new_user_info.profile_image = request.FILES['profile_image']
                new_user_info.save()

                messages.success(request, "Profile image uploaded successfully.")
                return redirect('user_registration:user_profile', id=id)
        else:
            form = UserInfoForm(instance=user_info)

    except User.DoesNotExist:
        messages.error(request, "User does not exist.")
        return redirect('user_registration:user_login')

    return render(request, 'user_registration/upload_profile_image.html', {'form': form})





"""This function updates profile page"""
@login_required
def update_profile(request, id):
    try:
        user = get_object_or_404(User, id=id)
        user_info = get_object_or_404(UserInfo, user=user)

        user_form = UserUpdateForm(instance=user)
        info_form = UserInfoForm(instance=user_info)

        if request.method == "POST":
            try:
                user_form = UserUpdateForm(request.POST, instance=user)
                info_form = UserInfoForm(request.POST, instance=user_info)

                if user_form.is_valid() and info_form.is_valid():
                    user_obj = user_form.save(commit=False)
                    user_obj.username = user.username
                    user_obj.email = user.email
                    user_obj.password = user.password
                    user_obj.save()

                    info_form.save()
                    messages.success(request, "Your profile updated successfully!!")
                    return redirect("user_registration:user_profile", id=id)
                else:
                    for field_errors in user_form.errors.values():
                        for error in field_errors:
                            messages.error(request, error)
                    
                    for field_errors in info_form.errors.values():
                        for error in field_errors:
                            messages.error(request, error)
                            
            except Exception as e:
                messages.error(request, f"Error: {str(e)}")
    except User.DoesNotExist:
        messages.error(request, "This User Does Not Exist!")
        return redirect("user_registration:user_login")

    return render(
        request,
        "user_registration/update_profile.html",
        {"user_form": user_form, "info_form": info_form},
    )
    
    
@login_required 
def user_list(request):
    users = User.objects.select_related("userinfo").exclude(username='admin')
    return render(request, "user_registration/user_list.html", {'users':users})

user_registration/templates/user_registration/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description%}{% endblock %}">
    <meta name="robots" content="{% block robots%}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'user_registration/style.css'%}">
    <link rel="icon" type="image/x-icon" href="{% static "image/question.ico" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

<!-- fontawsome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar" id="my-main-nav">
        
        <a href="{% url 'user_registration:index' %}"><img src="{% static "image/logo-no-background.svg" %}" width="50" alt="logo"></a>
       
        
         <ul class="nav-links">
 
          
           <input type="checkbox" id="checkbox-toggle">
           <label for="checkbox-toggle" class="hamburger">&#9776;</label>
        
         
         <div class="menu">
            {% if user.is_authenticated %}
           <li><a href="{% url 'quiz:quiz_index' %}" >Quiz Home</a></li>
           <li><a href="{% url 'user_registration:user_profile' user.id %}">Profile</a></li>
           <li class="dropdown-menu">
            <a href="#">Quiz <i class="fa fa-sort-down"></i> </a>

            <ul class="dropdown">
              <li><a class='dropdown-link' href="{% url 'quiz:create_quiz_category' %}">Create Category</a></li>
              <li><a class='dropdown-link' href="{% url 'quiz:add_quiz_question' %}">Add Questions</a></li>
              <li><a class='dropdown-link' href="{% url 'quiz:show_quiz_category' %}">Show Quiz Category</a></li>
              <li><a class='dropdown-link' href="{% url 'quiz:show_quiz_question' %}">Show Quiz Question</a></li>
              <li><a class='dropdown-link' href="{% url 'user_registration:user_list' %}">Show User List</a></li>
            </ul>
          </li>
           <li><a href="{% url 'user_registration:user_logout' %}">Logout</a></li>
           <li><a href="{% url 'user_registration:change_password' user.id %}">Change Password</a></li>
 
           
           {% else %}
           <li><a href="{% url 'user_registration:index' %}" >Home</a></li>
           <li><a href="{% url 'user_registration:register' %}">Signup</a></li>
           <li><a href="{% url 'user_registration:user_login' %}">Login</a></li>
           {% endif %}
           <div class="dark-mode">
            <svg onclick="darkMode()" viewBox="0 0 512 512" width="25px" id="sun-icon">
              <g id="Sun">
                  <path d="M255.8,120a136,136,0,1,0,136,136.05v0A136.17,136.17,0,0,0,255.8,120Z" style="fill:#1e1e1e"/>
                  <path d="M472,232H440a24,24,0,0,0,0,48h32a24,24,0,0,0,0-48Z" style="fill:#1e1e1e"/>
                  <path d="M255.8,416a24,24,0,0,0-24,24v32a24,24,0,1,0,48,0V440A24,24,0,0,0,255.8,416Z" style="fill:#1e1e1e"/>
                  <path d="M96,256.05a24,24,0,0,0-24-24H40a24,24,0,1,0,0,48H72A24,24,0,0,0,96,256.05Z" style="fill:#1e1e1e"/>
                  <path d="M255.8,96a24,24,0,0,0,24-24V40a24,24,0,0,0-48,0V72a24,24,0,0,0,24,24Z" style="fill:#1e1e1e"/>
                  <path d="M402.89,142.87l22.63-22.63a24,24,0,0,0-33.85-34l-.07.07L369,109a24,24,0,0,0,33.86,34Z" style="fill:#1e1e1e"/>
                  <path d="M402.89,369.22a24,24,0,0,0-34,33.87l.06.05,22.63,22.63a24,24,0,0,0,34-33.86l-.06-.06Z" style="fill:#1e1e1e"/>
                  <path d="M108.7,369.22,86.07,391.85a24,24,0,1,0,33.85,34l.07-.07,22.63-22.63a24,24,0,1,0-33.86-34Z" style="fill:#1e1e1e"/>
                  <path d="M108.7,142.87a24,24,0,1,0,34-33.89l0,0L120,86.32a24,24,0,1,0-34,33.83l.09.09Z" style="fill:#1e1e1e"/>
              </g>
          </svg>
          
            <svg onclick="lightMode()" viewBox="0 0 312.81 311.51" width="20px" id="moon-icon">
              <path d="M305.2,178.16a11,11,0,0,0-9.2,2A117.36,117.36,0,0,1,260.4,201a111.48,111.48,0,0,1-40.4,7.2A117.45,117.45,0,0,1,102.4,90.56a123.27,123.27,0,0,1,6.4-38.8A107.41,107.41,0,0,1,128,17.36,10.21,10.21,0,0,0,126.4,3a11,11,0,0,0-9.2-2,161.41,161.41,0,0,0-84.8,56.8,158.38,158.38,0,1,0,280,132.8A9.71,9.71,0,0,0,305.2,178.16Z" transform="translate(0 -0.65)" style="fill:#1e1e1e"/>
          </svg>
           </div>
           
         
         </div>
       </ul> 
         </nav>
    
    {% block body %}{% endblock %}
    <script src="{% static 'user_registration/index.js' %}"></script>
</body>
</html>

user_registration/templates/user_registration/change_password.html
{% extends 'user_registration/base.html' %}
{% load static %}
    {% block description %}change{% endblock%}
    {% block robots %}index, follow {% endblock %}
    {% block keywords %}Chanage Password, Quiz Application{% endblock %}
    {% block title %}Home{% endblock %}
    {% block body %}

    {% include "includes/error.html" %}

    
<section class="change-password">
    <h1 class="title">Change Password Here!</h1>
    <form method="POST">
        {% csrf_token %}
        {{ password_form.as_p }}
        <input type="submit" value="Save Changes">
    </form>
</section>
{% endblock body %}

user_registration/templates/user_registration/index.html
{% extends 'user_registration/base.html' %}
{% load static %}
    {% block description %}Index page quiz application{% endblock%}
    {% block robots %}index, follow {% endblock %}
    {% block keywords %}Home, Quiz Application{% endblock %}
    {% block title %}Home{% endblock %}
    {% block body %}
   
<section class='index-page'>
    
    <div class="welcome-section">
        <h1 class="title">Welcome {{ user.first_name | capfirst}} to Quiz Application!</h1>
        <h3>You can make your own tests that you can play with your loved ones. By taking this quiz, you can prove that you're the smartest person on the planet.</h3>
    <div class="index-buttons">
        <a href="{% url 'user_registration:register' %}"><button class="sm-button">Signup</button></a>
        <a href="{% url 'user_registration:user_login' %}"><button class="sm-button">Login</button></a>
        
    </div>
    
    </div>

    <div class='index-images'>
        <div class="item a">
            <img src="{% static "image/quiz.png" %}" alt="quiz">
        </div>
        <div class="item b">
            <img src="{% static "image/bulb.png" %}" alt="myshop logo">
        </div> 
        <div class="item c">
            <img src="{% static "image/girl-with-computer.jpeg" %}" alt="myshop logo">
        </div>
        <div class="item d">
            <img src="{% static "image/kids-with-computer.jpeg" %}" alt="myshop logo">
        </div>
        <div class="item e">
            <img src="{% static "image/quiztime.jpeg" %}" alt="quiztime">
        </div>
    </div>
    
</section>
{% endblock body %}

user_registration/templates/user_registration/login.html
{% extends "user_registration/base.html" %}
{% load static %}
    {% block description %}You can login to quiz application from here{% endblock%}
    {% block robots %}index, follow {% endblock %}
    {% block keywords %}Login, Quiz Application{% endblock %}
    {% block title %}Login{% endblock %}
    {% block body %}

    {% include "includes/error.html" %}
        

        <h1 class="title">Please Login!</h1>
    <form action="{% url 'user_registration:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
    </section>
    {% endblock %}

user_registration/templates/user_registration/register.html
{% extends 'user_registration/base.html' %}
{% load static %}
{% block description %}Sign up for a new account on quiz application{% endblock%}
    {% block robots %}register, follow {% endblock %}
    {% block keywords %}Signup, Quiz Application{% endblock %}
    {% block title %}Signup{% endblock %}
    {% block body %}

    <h1 class="title">Please fill the form and Register</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ info_form.as_p }}

        <input type="submit" value="Register">
    </form>
    
{% endblock %}

user_registration/templates/user_registration/update_profile.html
{% extends 'user_registration/base.html' %}
{% load static %}
    {% block description %}Updae user profile quiz application {% endblock %}
    {% block robots %}index, follow{% endblock %}
    {% block keywords %}Update Profile, Quiz Application{% endblock  %}
    {% block title %}Update profile{% endblock  %}
    {% block body %}

    <h1 class="title">Update your profile {{ user.first_name }}</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        {{ user_form.first_name.label_tag }}
        {{ user_form.first_name }}
        {{ user_form.last.label_tag }}
        {{ user_form.last_name }}
        {{ info_form.address.label_tag }}
        {{ info_form.address }}
        {{ info_form.phone.label_tag }}
        {{ info_form.phone }}
        <input type="submit" value='Update'>

    </form>

    {% endblock %}

user_registration/templates/user_registration/upload_profile_image.html
{% extends 'user_registration/base.html' %}
{% load static %}
    {% block title %}Upload Image{% endblock  %}
{% block body %}


  <h1 class="title">Upload Profile Image</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="upload-image">
      <label for="id_profile_image">Profile Image:</label>
      <input type="file" name="profile_image" id="id_profile_image">
      <button>Upload</button>
    </div>
  </form>
{% endblock %}

user_registration/templates/user_registration/user_list.html
{% extends "user_registration/base.html" %}
{% load static %}

{% block title %}User List{% endblock %}

{% block body %}
<section class="user-card-container">
  <h1 class='title'>Users</h1>
  <div class="user-card">
    {% for user in users %}
    <div class="user-card-profile">
      <img class="card-image" src="{{ user.userinfo.profile_image.url }}" alt="Profile Image" width="100" height="100">
      <p>{{ user.username }}</p>
      <a href="#"><button class="link-button" data-modal-id="modal-container{{ forloop.counter }}">See Profile</button></a>
    </div>
    {% endfor %}
  </div>
</section>

{% for user in users %}
<div class="modal-container" id="modal-container{{ forloop.counter }}">
  <div class="modal">
    <div class="modal-header">
      <h2>{{ user.first_name|capfirst }}'s Profile</h2>
      <i class="fa fa-close" id="close-icon{{ forloop.counter }}"></i>
    </div>
    <div class="modal-content">
      <img src="{{ user.userinfo.profile_image.url }}" alt="Profile Image">
      <p>
        Name: {{ user.first_name }} {{ user.last_name }}
      </p>
      <p>
        Email: {{ user.email }}
      </p>
      <p>
        Address: {{ user.userinfo.address }}
      </p>
      <p>
        Phone: {{ user.userinfo.phone }}
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn-close" id="close-btn{{ forloop.counter }}">Close</button>
    </div>
  </div>
</div>
{% endfor %}


{% endblock %}

user_registration/templates/user_registration/user_profile.html
{% extends 'user_registration/base.html' %} 
{% load static %} 
{% block description %}User Profile Quiz Application{% endblock%} 
{% block robots %}Profile, follow {% endblock %} 
{% block keywords %}Profile, Quiz Application{% endblock %} 
{% block title %}User Profile{% endblock %} 

{% block body %}

{% include "includes/error.html" %}

<div class="profile-page">
  <div class="flex-item">
    <div class="user-profile">
      <h1 class="title">User Profile</h1>
      <p><strong>Username:</strong> @<em>{{ user.username }}</em></p>
      <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</p>
      <p><strong>Email:</strong> {{ user.email }}</p>
      <p><strong>Address:</strong> {{ user_info.address }}</p>
      <p><strong>Phone:</strong> {{ user_info.phone }}</p>
      {% if user_info.profile_image %}
      <img
        width="200"
        src="{{ user_info.profile_image.url }}"
        alt="{{ user_info.user.get_full_name }} Profile Image"
      />
      {% else %}
      <img
        width="200"
        src="{% static 'image/no-image.svg' %}"
        alt="Add Image"
      />
      {% endif %}
      <p>
        <a class='link-button' href="{% url 'user_registration:upload_profile_image' user.id %}"
          >Change Image</a
        >
      </p>
      <p>
        <a class='link-button' href="{% url 'user_registration:update_profile' user.id %}"
          >Update Profile</a
        >
      </p>
    </div>
  </div>
</div>
{% endblock %}