quiz/urls.py
from django.urls import path
from . import views


app_name = 'quiz'

urlpatterns = [
    path('create_quiz_category/', views.create_quiz_category, name='create_quiz_category'),
    path('add_quiz_question/', views.add_quiz_question, name='add_quiz_question'),
    path('show_quiz_question/', views.show_quiz_question, name='show_quiz_question'),
    path('quiz_index/', views.quiz_index, name='quiz_index'),
    path('delete_quiz_question/<int:question_id>/', views.delete_quiz_question, name='delete_quiz_question'),
    path('update_quiz_category/<int:category_id>/', views.update_quiz_category, name='update_quiz_category'),
    path('show_quiz_category/', views.show_quiz_category, name='show_quiz_category'),
    path('delete_quiz_category/<int:category_id>', views.delete_quiz_category, name='delete_quiz_category'),
    path('add_answer_to_questions/<int:question_id>/', views.add_answer_to_questions, name='add_answer_to_questions'),
    
    
    path('view_quiz/<int:category_id>/', views.view_quiz, name='view_quiz'),
    path('submit_quiz/<int:category_id>/', views.submit_quiz, name='submit_quiz'),
    path('quiz_result/<int:category_id>/<int:user_score_id>/', views.quiz_result, name='quiz_result'),

    
    
]

quizapplication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_registration.urls')),
    path('quiz/', include('quiz.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_registration/urls.py
from django.urls import path
from . import views

app_name = 'user_registration'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_profile/<int:id>/', views.user_profile, name="user_profile"),
    path('change_password/<int:id>/', views.change_password, name='change_password'),
    path('upload_profile_image/<int:id>/', views.upload_profile_image, name='upload_profile_image'),
    path('update_profile/<int:id>/', views.update_profile, name='update_profile'),
    path('user_list/', views.user_list, name='user_list'),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User

class QuizCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="Duration in Seconds", default=1)
    
    class Meta:
        verbose_name_plural = "quiz catogeries"
    
    def __str__(self):
        return self.name
    
    def get_question(self):
        return self.question_set.all()


class Question(models.Model):
    content = models.CharField(max_length=255)
    quiz_category = models.ForeignKey(QuizCategory, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.content} ----------------------------- {self.quiz_category}"
    
    def get_answers(self):
        return self.answer_set.all()
    
    def save(self, *args, **kwargs):
        if self.pk is None:
            num_existing_questions = Question.objects.filter(quiz_category=self.quiz_category).count()
            if num_existing_questions >= self.quiz_category.number_of_questions:
                raise ValueError(f"You cannot create more questions then {self.quiz_category.number_of_questions} questions in this category.")
        super().save(*args, **kwargs)
            
    
    
class Answer(models.Model):
    content = models.CharField(max_length=200)
    correct_answer = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Question: {self.question.content}, answer: {self.content}, Correct Answer: {self.correct_answer}"
    

class UserScore(models.Model):
    quiz_category = models.ForeignKey(QuizCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField()
    
    def __str__(self):
        return f"{self.user} - {self.quiz_category}"
    
    

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .form import QuizCategoryForm, QuestionForm
from django.contrib.auth.decorators import login_required
from .models import Question, QuizCategory, Answer, UserScore
from django.contrib import messages
from django.forms import inlineformset_factory





@login_required
def quiz_index(request):
    quiz_categories = QuizCategory.objects.all()
    return render(request, "quiz/quiz_index.html", {'quiz_categories':quiz_categories})

""" This function creates quiz category """

@login_required
def create_quiz_category(request):
    if request.method == 'POST':
        form = QuizCategoryForm(request.POST)
        if form.is_valid():
            category_name = form.cleaned_data['name']
            if not QuizCategory.objects.filter(name=category_name).exists():
                form.save()
                messages.success(request, "Your Quiz Category Has Been Created.")
                return redirect('quiz:quiz_index')
            else:
                messages.error(request, "The Quiz Category Already Exists.")
        else:
            messages.error(request, "Your Form Data Is Invalid.")
    else:
        form = QuizCategoryForm()
    return render(request, 'quiz/create_quiz_category.html', {'form': form})






""" This function adds quizes in database """
@login_required
def add_quiz_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                form = QuestionForm()
                messages.success(request, "Your quiz question has been added successfully.")
            except ValueError as e:
                error_msg = str(e)
                messages.error(request, error_msg)
    else:
        form = QuestionForm()
    return render(request, "quiz/add_quiz_question.html", {'form':form}) 


def show_quiz_question(request):
    questions = Question.objects.all()
    return render(request, "quiz/show_quiz_question.html", {'questions':questions})


""" This function deletes the quiz questions """
@login_required
def delete_quiz_question(request, question_id):
    try:
        question = Question.objects.get(id=question_id)
        question.delete()
        messages.success(request, "The quiz question has been deleted successfully.")
    except Question.DoesNotExist:
        messages.error(request, "The quiz question does not exist.")
    return redirect('quiz:show_quiz_question')


@login_required
def delete_quiz_category(request, category_id):
    try:
        category = QuizCategory.objects.get(id=category_id)
        category.delete()
        messages.success(request, "The quiz category has been deleted successfully.")
    except Question.DoesNotExist:
        messages.error(request, "The quiz category does not exist.")
    return redirect('quiz:show_quiz_category')


@login_required
def show_quiz_category(request):
    quiz_categories = QuizCategory.objects.all()
    return render(request, "quiz/show_quiz_category.html", {'quiz_categories':quiz_categories})

    
@login_required
def update_quiz_category(request, category_id):
    quiz_category = get_object_or_404(QuizCategory, id=category_id)
    
    if request.method == 'POST':
        form = QuizCategoryForm(request.POST, instance=quiz_category)
        if form.is_valid():
            category_name = form.cleaned_data['name']
            if not QuizCategory.objects.filter(name=category_name).exclude(id=category_id).exists():
                form.save()
                messages.success(request, "The quiz category has been updated successfully.")
                return redirect('quiz:show_quiz_category')
            else:
                messages.error(request, "The quiz category already exists.")
        else:
            messages.error(request, "The form data is invalid.")
    else:
        initial_val = {
            'name': quiz_category.name,
            'description': quiz_category.description,
            'number_of_questions': quiz_category.number_of_questions,
            'time': quiz_category.time,
        }
        form = QuizCategoryForm(instance=quiz_category, initial=initial_val)
    return render(request, "quiz/update_quiz_category.html", {'form': form})



@login_required
def add_answer_to_questions(request, question_id):
    question = Question.objects.get(id=question_id)
    question_form_set = inlineformset_factory(Question, Answer, fields=('content', 'correct_answer', 'question'), extra=4, max_num=4)
    if request.method == 'POST':
        form = question_form_set(request.POST, instance=question)
        if form.is_valid():
            form.save()
            messages.success(request, "Added Successfully.")
            return redirect('quiz:show_quiz_question')
    else:
        form = question_form_set(instance=question)
    return render(request, "quiz/add_answer_to_questions.html", {'form':form, 'question':question})



@login_required
def view_quiz(request, category_id):
    try:
        category = get_object_or_404(QuizCategory, id=category_id)
        questions = category.get_question()
        return render(request, "quiz/view_quiz.html", {'category': category, 'questions': questions})
    except QuizCategory.DoesNotExist:
        messages.error(request, "Quiz category does not exist.")
        return redirect('quiz:quiz_categories')


@login_required
def submit_quiz(request, category_id):
    if request.method == 'POST':
        try:
            category = get_object_or_404(QuizCategory, id=category_id)
            questions = category.get_question()
            score = 0
            total_questions = 0

            for question in questions:
                total_questions += 1
                selected_answer_id = request.POST.get(f'question_{question.id}')
                try:
                    selected_answer = get_object_or_404(Answer, id=selected_answer_id)
                except Answer.DoesNotExist:
                    error_message = "Selected answer does not exist."
                    return render(request, 'error.html', {'error_message': error_message})

                if selected_answer.correct_answer:
                    score += 1

            percentage = (score / total_questions) * 100
            user_score = UserScore.objects.create(quiz_category=category, user=request.user, score=score)

            context = {
                'category': category,
                'category_id': category_id,
                'questions': questions,
                'user_score_id': user_score.id,
                'percentage': percentage,
                'duration': category.time,
            }
            return redirect('quiz:quiz_result', category_id=category_id, user_score_id=user_score.id)
        except QuizCategory.DoesNotExist:
            error_message = "Quiz category does not exist."
            return render(request, 'error.html', {'error_message': error_message})
    else:
        error_message = "Invalid request method."
        return render(request, 'error.html', {'error_message': error_message})



@login_required
def quiz_result(request, category_id, user_score_id):
    try:
        category = get_object_or_404(QuizCategory, id=category_id)
        user_score = get_object_or_404(UserScore, id=user_score_id, quiz_category=category, user=request.user)
        total_questions = category.number_of_questions
        percentage = (user_score.score / total_questions) * 100

        context = {
            'category': category,
            'user_score': user_score,
            'total_questions': total_questions,
            'percentage': percentage,
        }

        return render(request, "quiz/quiz_result.html", context)
    except (QuizCategory.DoesNotExist, UserScore.DoesNotExist):
        messages.error(request, "Quiz result not found.")
        return redirect('quiz:quiz_categories')

quiz/templates/quiz/add_answer_to_questions.html
{% include 'user_registration/base.html' %} 
{% load static %}
<style>
    input {
        margin-bottom: 15px;
        text-align:center;
    }
   input["checkbox"]{
    margint-bottom:20px;
   }
   p {
    text-align: center;
   }
   .back-button {
    margin: 10px auto;
   }
</style>

{% block body %}

{% include "includes/error.html" %}

<h1 class="title">Add Answers To the Questions</h1>

<form action="">
    <a class='back-button' href="{% url 'quiz:show_quiz_question' %}">Back</a>
    <p> <strong>Question: </strong> {{question.content}}</p>
    <p><strong>Category: </strong>{{question.quiz_category}}</p>
</form>

<form action="{% url 'quiz:add_answer_to_questions' question.id %}" method="POST">
    <p style='text-align:center;'>Add your answers here.</p>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
    
</form>



{% endblock %}

quiz/templates/quiz/add_quiz_question.html
{% load static %}
{% include 'user_registration/base.html' %}
{% block body %}

{% include "includes/error.html" %}
<div class="add-question">
    <h1 class="title">Add Quiz Questions</h1>
    <form id="question-form" action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add">
        <a href="{% url 'quiz:show_quiz_question' %}">Show Questions</a>
    </form>
   
</div>

{% endblock  %}

quiz/templates/quiz/create_quiz_category.html
{% include 'user_registration/base.html' %}
{% load static %}
{% block body %}
{% include "includes/error.html" %}


<h1 class="title">Create Quiz Category</h1>


<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
</form>
{% endblock  %}

quiz/templates/quiz/quiz_index.html
{% include 'user_registration/base.html' %} 
{% load static %}
<style>
  


  
</style>
{% block body %}

{% include "includes/error.html" %}

<section class="index-page">
  
  <div class="welcome-section">
    <h1 class="title">
      Welcome {{ user.first_name | capfirst}} to Quiz Application!
    </h1>
    <h3>Play Online Quiz And Have Fun With Your Family & Friends</h3>
    {% comment %} <input class type="text" placeholder="@User name" /> {% endcomment %}
    <a href="{% url 'user_registration:user_list' %}"><button class="sm-button">See User List</button></a>
  </div>

  
<div class="card-box" style="display:flex; flex-wrap:wrap;justify-content:space-between; flex-basis: calc(33.33% - 10px);">

  {% for category in quiz_categories %}
  
  <div class="play-quiz">
    <div class="card-2">
      <h3>{{ category.name }}</h3>
   
      <a style="text-decoration: none; color:black; font-weight:900" href="{% url 'quiz:view_quiz' category.id %}"><input style="width:100px; font-size:12px;" type="submit" value="Play Quiz"></a>
    </div>
  </div>

{% endfor %}

</div>
  
  
</section>
{% endblock %}

quiz/templates/quiz/quiz_result.html
{% include 'user_registration/base.html' %}
{% load static %}

{% block body %}
<div class="result">
<div class="quiz-result">
<h1>Quiz Result</h1>
<h2>Category: {{ category.name }}</h2>
<br>
<p>Thank you {{user.first_name}} for playing the quiz, your scores are below:</p>
<br>
<p>Total Questions: {{ total_questions }}</p>
<p>Your Score: {{ user_score.score }}</p>
<p>Percentage: {{ percentage }}%</p>


</div>
</div>
{% endblock %}

quiz/templates/quiz/show_quiz_category.html
{% include 'user_registration/base.html' %}
{% load static %}

{% block body %}
{% include "includes/error.html" %}

  
    <h1 class="title">Quiz Categories</h1>
    <a class='back-button' href="{% url 'quiz:quiz_index' %}">Home</a>
    <table class="quiz-question-view">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>No. of Ques.</th>
                <th>Time in Sec.</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_category in quiz_categories %}
            <tr>
                <td>{{ quiz_category.name }}</td>
                <td>{{ quiz_category.description }}</td>
                <td style="text-align:center;">{{ quiz_category.number_of_questions }}</td>
                <td style="text-align:center;"> {{ quiz_category.time }}</td>
                <td style="text-align:center; width:100px">
                    
                    <form style="
                        width: 40px;
                        background-color: none;
                        border: none;
                        border-radius: none;
                        color: none;
                        padding: 0 0 0 0;
                        margin: 0 0 0 0;
                    " method="POST" action="{% url 'quiz:update_quiz_category' quiz_category.id %}">
                        {% csrf_token %}
                        <button style="background-color:green;" class="del-button" type="submit">Update</button>
                    </form> <br>
                    <form style="
                    width: 40px;
                    background-color: none;
                    border: none;
                    border-radius: none;
                    color: none;
                    padding: 0 0 0 0;
                    margin: 0 0 0 0;
                " method="POST" action="{% url 'quiz:delete_quiz_category' quiz_category.id %}">
                    {% csrf_token %}
                    <button style="background-color:red;" class="del-button" type="submit">Delete</button>
                </form>
                </td>
                    
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No questions added yet.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

  
    {% endblock  %}

quiz/templates/quiz/show_quiz_question.html
{% include 'user_registration/base.html' %}
{% load static %}

{% block body %}
{% include "includes/error.html" %}


    <h1 class="title">Quiz Questions</h1>
    <a class='back-button' href="{% url 'quiz:add_quiz_question' %}">Back</a>
    <table class="quiz-question-view">
        <thead>
            <tr>
                <th>Question</th>
                <th>Category</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for question in questions %}
            <tr>
               <td><a href="{% url 'quiz:add_answer_to_questions' question.id %}">{{ question.id }} - {{ question.content }}</a> </td>
                <td style="text-align:center;">{{ question.quiz_category }}</td>
                <td style="text-align:center;">
                    <form style="
                        margin:auto;
                        width: 40px;
                        background-color: none;
                        border: none;
                        border-radius: none;
                        color: none;
                        padding: 0 0 0 0;
                        margin: 0 0 0 0;
                    " method="POST" action="{% url 'quiz:delete_quiz_question' question.id %}">
                        {% csrf_token %}
                        <button class="del-button" type="submit">Delete</button>
                    </form>
                </td>
                    
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No questions added yet.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

  
    {% endblock  %}

quiz/templates/quiz/update_quiz_category.html
{% include 'user_registration/base.html' %} 
{% load static %}

{% block body %}

{% include "includes/error.html" %}

<h1 class="title">Update Quiz Category</h1>

    <form action="" method="POST">
      {% csrf_token %}
      <label for="id_name">Name:</label>
      <input type="text" id="id_name" name="name" value="{{ form.initial.name }}">
      
      <label for="id_description">Description:</label>
      <textarea id="id_description" name="description">{{ form.initial.description }}</textarea>
      
      <label for="id_number_of_questions">Number of Questions:</label>
      <input type="number" id="id_number_of_questions" name="number_of_questions" value="{{ form.initial.number_of_questions }}">
      
      <label for="id_time">Time:</label>
      <input type="text" id="id_time" name="time" value="{{ form.initial.time }}">
      
      <input type="submit" value="Update">
    </form> 

{% endblock %}

quiz/templates/quiz/view_quiz.html
{% include 'user_registration/base.html' %}
{% load static %}


{% block body %}
<div class='quiz-view'>
<h1>Category: {{ category.name }}</h1>
<p>Description: {{ category.description }}</p>

<p id='timer'></p>
</div>
<form method="POST" action="{% url 'quiz:submit_quiz' category_id=category.id %}">
    {% csrf_token %}
    {% for question in questions %}
        <h3>{{ question.content }}</h3>
        {% for answer in question.get_answers %}
            <input type="radio" id="{{ answer.id }}" name="question_{{ question.id }}" value="{{ answer.id }}">
            <label for="{{ answer.id }}">{{ answer.content }}</label><br>
        {% endfor %}
        <br>
    {% endfor %}
    <input type="submit" value="Submit">
</form>



<script>
   
    function handleQuizSubmission(categoryId, userScoreId, duration) {
      const timerElement = document.getElementById("timer");
      let timeRemaining = duration;
    
      function updateTimer() {
        const minutes = Math.floor(timeRemaining / 600);
        const seconds = timeRemaining % 60;
        timerElement.textContent = `Time Remaining: ${minutes}:${seconds
          .toString()
          .padStart(2, "0")}`;
    
        if (timeRemaining <= 0) {
          alert("Time's up!");
          submitQuiz();
        } else {
          timeRemaining--;
          setTimeout(updateTimer, 1000);
        }
      }
      function submitQuiz() {
        const form = document.getElementById("quiz-form");
        form.submit();
      }

      document.addEventListener("DOMContentLoaded", function () {
        updateTimer();
      });
    }
 
    const categoryId = {{ category.id }};
    const userScoreId = {{ user_score_id }};
    const duration = {{ category.time }};
    

    document.addEventListener("DOMContentLoaded", function () {
      handleQuizSubmission(categoryId, userScoreId, duration);
    });
  </script>
  
  
  
  
  
  
{% endblock %}